<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="downloadtask" nsURI="http://www.example.org/DownloadTask/1.0"
    nsPrefix="downloadtask">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="schemaLocation" value="file:///C:/oomph/server/model/Downloadtask-1.0.ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DownloadTask" eSuperTypes="http://www.eclipse.org/oomph/setup/1.0#//SetupTask">
    <eAnnotations source="http://www.eclipse.org/oomph/setup/Enablement">
      <details key="variableName" value="p2.download"/>
      <details key="repository" value="file:///C:/oomph/server/"/>
      <details key="installableUnits" value="DownloadTask.feature.group"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/oomph/setup/ValidTriggers">
      <details key="triggers" value="BOOTSTRAP STARTUP MANUAL"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceLocation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connectionTimeout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1000"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readTimeout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1500"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destinationPath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destinationFile" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="500"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="estimatedSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
  </eClassifiers>
</ecore:EPackage>
